site_name: HEMI
site_description: Proyecto de evaluación de medidas de inflación en MATLAB. Realizado por el Departamento de Investigaciones Económicas del Banco de Guatemala.
repo_url: https://github.com/DIE-BANGUAT/EMI-docs
nav:
    - HEMI: 
        - index.md
    - Principal:
        - Introducción: cuerpo/introduccion.md
        - Justificación: cuerpo/justificacion.md
    - Calibración: 
        - Especificación y calibración del factor de tendencia estocástica : calibracion/Calibración varianza RW.md
        - Selección del número de simulaciones: calibracion/Selección simulaciones.md
        - Selección de la medida de evaluación: calibracion/Determinación medida evaluación.md
        - Remuestreo con block bootstrap: calibracion/Remuestreo block bootstrap.md
    - Evaluación: 
        - Criterios de evaluación y pruebas de sensibilidad: evaluacion/criterios-de-evaluacion.md
        - Evaluación de las medidas de inflación total: evaluacion/inflaciones-totales.md
        - Evaluación de las medidas basadas en percentiles: evaluacion/evaluacion-percentiles.md
        - Evaluación de las medidas basadas en exclusión fija: evaluacion/evaluacion-exclusion-fija.md
        - Evaluación de las medidas basadas en medias truncadas: evaluacion/evaluacion-medias-truncadas.md
        - Evaluación de las medidas basadas en metodología de subyacente MAI: evaluacion/evaluacion-mai.md
        - Evaluación de las medidas basadas en exclusión dinámica: evaluacion/sub-dinamica.md
        - Combinaciones lineales de medidas de inflación óptimas: evaluacion/combinacion-lineal.md
        - Conformación de intervalos de confianza para el nivel de inflación: evaluacion/intervalos-confianza.md

theme: 
    name: readthedocs
    highlightjs: true
    hljs_style: "Tomorrow"
    hljs_languages:
        - matlab
        - python

markdown_extensions:
    - footnotes
    - pymdownx.arithmatex
    - toc:
        baselevel: 2
        permalink: True

extra_javascript: 
    - js/extra.js
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML